In [1]:
import requests
from sqlite3 import connect
import pandas as pd

conn = connect("../StocksPlatform/app.db")

In [50]:
symbols = pd.read_sql_query("SELECT Name, Symbol, Country FROM Assets", conn)
symbols = symbols[(symbols["Country"] == "Norway")]
symbols

                                          Name    Symbol Country
41                         Genetic Analysis AS      GEAN  Norway
71                 GULF KEYSTONE PETROLEUM LTD       GKP  Norway
112    CONSTELLATION OIL SERVICES HOLDING S.A.      COSH  Norway
129                               REFUELS N.V.      REFL  Norway
162                       SPAREBANK 1 NORDMØRE      SNOR  Norway
...                                        ...       ...     ...
11956                                 CYVIZ AS     CYVIZ  Norway
12079                ELLIPTIC LABORATORIES ASA     ELABS  Norway
12156                        TEKNA HOLDING ASA     TEKNA  Norway
12200                            STOLT-NIELSEN       SNI  Norway
12304              Norwegian Krone / US Dollar  NOKUSD=X  Norway

[293 rows x 3 columns]

In [51]:
symbols[symbols["Symbol"] == "EQNR"]

         Name Symbol Country
6045  EQUINOR   EQNR  Norway

In [55]:
symbols_concat = ""
# responses = []
base_url = "https://api.e24.no/bors/tags?symbols=" # EQNR.OSE,YAR.OSE,AAPL.NAS
for i, row in symbols.iterrows():
    if row["Country"] == "United States":
        symbols_concat += f"{row['Symbol']}.NAS,"
    elif row["Country"] == "Norway":
        symbols_concat += f"{row['Symbol']}.OSE,"
    if i % 9 == 9 - 1:
        print("Fetching E24 tag IDs for symbols: " + symbols_concat[:-1])
        response = requests.get(base_url + symbols_concat[:-1])
        response_json = response.json()
        symbols_concat = ""
        responses.append(response_json)

Fetching E24 tag IDs for symbols: GEAN.OSE,GKP.OSE
Fetching E24 tag IDs for symbols: COSH.OSE,REFL.OSE,SNOR.OSE,MAS.OSE,BSP.OSE,ABL.OSE,ITERA.OSE,ASA.OSE,ABTEC.OSE,EPR.OSE,ISLAX.OSE,MOWI.OSE,PCIB.OSE,DSRT.OSE
Fetching E24 tag IDs for symbols: APR.OSE,PNOR.OSE,EQVA.OSE,PLGC.OSE
Fetching E24 tag IDs for symbols: INDCT.OSE
Fetching E24 tag IDs for symbols: INSTA.OSE,BRUT.OSE,ENERG.OSE
Fetching E24 tag IDs for symbols: PLSV.OSE
Fetching E24 tag IDs for symbols: BORR.OSE,TRSB.OSE,NHY.OSE,KCC.OSE,KOMPL.OSE,BEWI.OSE,NKR.OSE,HYPRO.OSE,BRG.OSE,GSF.OSE
Fetching E24 tag IDs for symbols: 2020.OSE,MORG.OSE,ININ.OSE
Fetching E24 tag IDs for symbols: NISB.OSE
Fetching E24 tag IDs for symbols: CRNA.OSE,BWLPG.OSE,PLT.OSE,KRAB.OSE
Fetching E24 tag IDs for symbols: DOFG.OSE,RING.OSE,OTEC.OSE,SMCRT.OSE
Fetching E24 tag IDs for symbols: ARCH.OSE,HELG.OSE,NORBT.OSE
Fetching E24 tag IDs for symbols: STECH.OSE,NRC.OSE,TECH.OSE,NTG.OSE,OTOVO.OSE,SCATC.OSE
Fetching E24 tag IDs for symbols: AKOBO.OSE
Fetching E24 tag IDs for symbols: HGSB.OSE,ODL.OSE,SB1NO.OSE,VEND.OSE,ENDUR.OSE,STRO.OSE,HYN.OSE,TIETO.OSE,KMCP.OSE
Fetching E24 tag IDs for symbols: KOG.OSE,REACH.OSE,IOX.OSE,BONHR.OSE,SALME.OSE
Fetching E24 tag IDs for symbols: YAR.OSE,CAPSL.OSE,INIFY.OSE,PRS.OSE,NAPA.OSE,SBO.OSE,ATEA.OSE,CONTX.OSE,AKH.OSE,PARB.OSE,NORSE.OSE,MULTI.OSE,KING.OSE,STST.OSE
Fetching E24 tag IDs for symbols: BMA.OSE,ARR.OSE,KID.OSE,VAR.OSE,OSUN.OSE
Fetching E24 tag IDs for symbols: ODF.OSE
Fetching E24 tag IDs for symbols: AFG.OSE,SOFTX.OSE,ODFB.OSE,SPOG.OSE
Fetching E24 tag IDs for symbols: ZAL.OSE,LUMI.OSE,MELG.OSE,NOM.OSE,SALM.OSE,MVE.OSE,ELK.OSE
Fetching E24 tag IDs for symbols: EXTX.OSE,OMDA.OSE
Fetching E24 tag IDs for symbols: GYL.OSE,LYTIX.OSE,MORLD.OSE,FFSB.OSE,ONCIN.OSE,AKBM.OSE
Fetching E24 tag IDs for symbols: ENH.OSE,LIFE.OSE,HSHP.OSE,KOA.OSE,NYKD.OSE,CAVEN.OSE,SPOL.OSE
Fetching E24 tag IDs for symbols: ROGS.OSE,JAREN.OSE,SB68.OSE,ZENA.OSE,ANDF.OSE,BNOR.OSE,GIGA.OSE,SWON.OSE,DDRIL.OSE
Fetching E24 tag IDs for symbols: NTI.OSE,HEX.OSE
Fetching E24 tag IDs for symbols: DVD.OSE
Fetching E24 tag IDs for symbols: VTURA.OSE,NAS.OSE,SDSD.OSE,PSE.OSE,BOR.OSE,IDEX.OSE,BWE.OSE,EMGS.OSE
Fetching E24 tag IDs for symbols: AKRBP.OSE,SKAND.OSE,PEXIP.OSE,NEL.OSE,WSTEP.OSE,RANA.OSE,PUBLI.OSE,ALNG.OSE,NOHAL.OSE
Fetching E24 tag IDs for symbols: CADLR.OSE,GRONG.OSE,VISTN.OSE,EQNR.OSE,AGLX.OSE,ELMRA.OSE,NEXT.OSE,ORK.OSE,OCEAN.OSE,TRMED.OSE
Fetching E24 tag IDs for symbols: DNO.OSE
Fetching E24 tag IDs for symbols: AKER.OSE,NBX.OSE,BARRA.OSE,PRYME.OSE,SOGN.OSE
Fetching E24 tag IDs for symbols: WAWI.OSE,ELO.OSE,HKY.OSE,BWO.OSE,TEL.OSE,HUNT.OSE,BIEN.OSE
Fetching E24 tag IDs for symbols: NCOD.OSE,B2I.OSE,BOUV.OSE,GJF.OSE
Fetching E24 tag IDs for symbols: ABG.OSE,MPCES.OSE,ZLNA.OSE,VDI.OSE,HAUTO.OSE,VVL.OSE,NAVA.OSE,SUBC.OSE,NOFIN.OSE,SNTIA.OSE,AURG.OSE,AZT.OSE,CMBTO.OSE
Fetching E24 tag IDs for symbols: NORCO.OSE,BCS.OSE,PYRUM.OSE
Fetching E24 tag IDs for symbols: OBSRV.OSE,SOFF.OSE,AKVA.OSE,BALT.OSE,HPUR.OSE,SCANA.OSE,LSG.OSE,RECSI.OSE,GOD.OSE,HSPG.OSE
Fetching E24 tag IDs for symbols: TGS.OSE,HAVI.OSE,TINDE.OSE,ENTRA.OSE,ROM.OSE,PHO.OSE
Fetching E24 tag IDs for symbols: WEST.OSE,AASB.OSE,MPCC.OSE,OKEA.OSE,AUSS.OSE,5PG.OSE,JIN.OSE
Fetching E24 tag IDs for symbols: KLDVK.OSE,HUDL.OSE,ABS.OSE,SEA1.OSE,TOM.OSE,MING.OSE,ADS.OSE,WWIB.OSE
Fetching E24 tag IDs for symbols: ROMER.OSE,VEI.OSE,HBC.OSE,SATS.OSE,NOAP.OSE,CLOUD.OSE
Fetching E24 tag IDs for symbols: CODE.OSE,NOL.OSE,NONG.OSE,DNB.OSE,AFISH.OSE,SAGA.OSE,HAFNI.OSE,HDLY.OSE,AIX.OSE,OTL.OSE,ELIMP.OSE,AUTO.OSE,ACED.OSE,VOW.OSE,AKSO.OSE,XPLRA.OSE,ACR.OSE,MGN.OSE,PEN.OSE,CAMBI.OSE,LOKO.OSE,IWS.OSE,NORTH.OSE,NORDH.OSE,ZAP.OSE,NOSN.OSE,BAKKA.OSE,SOMA.OSE
Fetching E24 tag IDs for symbols: POL.OSE,NORAM.OSE,KIT.OSE,GENT.OSE,PROXI.OSE,PPG.OSE,DFENS.OSE
Fetching E24 tag IDs for symbols: ENSU.OSE,SMOP.OSE,PROT.OSE,AFK.OSE,EIOF.OSE,NSKOG.OSE,FRO.OSE,ENVIP.OSE,QEC.OSE,EAM.OSE
Fetching E24 tag IDs for symbols: OET.OSE,AKAST.OSE,MVW.OSE
Fetching E24 tag IDs for symbols: LINK.OSE,DELIA.OSE,NOD.OSE,HERMA.OSE,GEOS.OSE,SKUE.OSE,SBNOR.OSE,WWI.OSE

In [56]:
print("Fetching E24 tag IDs for symbols: " + symbols_concat[:-1])
response = requests.get(base_url + symbols_concat[:-1])
response_json = response.json()
symbols_concat = ""
responses.append(response_json)

Fetching E24 tag IDs for symbols: SOAG.OSE,HAV.OSE,STB.OSE,GEM.OSE,MEDI.OSE,RIVER.OSE,CYVIZ.OSE,ELABS.OSE,TEKNA.OSE,SNI.OSE,NOKUSD=X.OSE

In [60]:
symbol_e24tag_mapping = {}
for r in responses:
    for item in r["items"]:
        symbol = None
        for metadata in item["model"]["metadata"]:
            if "value" not in metadata: continue
            if "." in metadata["value"] and "www" not in metadata["value"]:
                symbol = metadata["value"]
                break
        if symbol:
            symbol = symbol.replace(".NAS", "").replace(".OSE", "")
            symbol_e24tag_mapping[symbol] = item["id"]
symbol_e24tag_mapping

{'SNOR': '7f6142bf-a28c-48ae-8740-17d5d1e718cd',
 'ITERA': '3e89fd54-7222-41e1-9dbb-bc005191bee3',
 'ABL': '4bb70596-3bd9-4c42-a46b-964b2c651091',
 'EPR': '6d9318cd-2a47-4b9f-bb42-330235f02754',
 'ASA': 'ba126a9e-2432-4023-8192-510283a447e8',
 'EQVA': '000825cd-ac0d-45f6-b8d9-ccfd1f70768c',
 'MOWI': 'd84adba1-ea4b-4b8b-953a-2a1dd09a1f0c',
 'LPG': '768bf4a2-a12c-43b3-a4d5-90991f0c1c94',
 'APR': '974fa226-62ed-4373-8871-75f62e221809',
 'PCIB': 'df1e6295-c179-40c6-8978-9d493591dcf5',
 'PNOR': 'fc696279-8d37-4296-845a-f6d51b9c3e17',
 'NHY': '59d15ea1-f991-4c05-b083-1032ab81168d',
 'KCC': '9afa0619-8ede-4ab1-b707-17aa6e34d5d0',
 'BORR': 'db3de1bb-2ca2-4a2a-86c0-c2a0400c095e',
 'HYPRO': '1d2243ed-dad2-48fc-86a5-533d391d6cb2',
 'NKR': 'a5eedeeb-b2dc-41ff-ad60-1848ed6f50c2',
 'KOMPL': '8860098b-d5e8-4171-b6c5-91b20bc75333',
 'BEWI': 'df8ac0a7-d3e6-4ddf-85f1-6e36ef6e270f',
 'MORG': '20541b88-031d-4b3e-a9fa-504a9ac18126',
 'GSF': 'c9eb25bf-90b6-4cdb-9457-4a74e9a6d0a4',
 '2020': '6609db43-beb8-4c7e-8406-82f950906d88',
 'BRG': '6e981f4b-0aa5-4502-9900-8c2592159626',
 'CRNA': 'f4596c50-6168-49ca-8c76-bf5372b1e7ea',
 'BWLPG': '0c8552c5-2054-41eb-a690-191d81e24505',
 'PLT': 'd54e2662-3147-4ccf-9430-8e96fdcc1974',
 'DOFG': '0ed55d81-9dc2-4a4a-a275-a5587c31c4cc',
 'OTEC': '22e06136-86ce-4084-9fdd-1ea171008e06',
 'SMCRT': '84f39a87-4fe2-473a-8d0c-7aa1cfd9ae84',
 'RING': 'b94c1dc6-f7be-46dd-9f35-044ca8a9e81f',
 'NORBT': '24007ab4-871c-4f5c-b25d-ace1d5e83cba',
 'ARCH': '7aed1888-1e63-4ffd-a431-d4e2e8d82d39',
 'NRC': '7f57d4c6-6077-4a26-88b6-aca86e1dfe5c',
 'HELG': 'b5b36a86-6fca-4331-b285-dd78f23a836d',
 'TECH': '2d9640be-c36d-4936-8646-8c4fe153e91d',
 'TSLA': 'd9ea85f7-09c6-4eff-8ebd-2cc178824f9f',
 'SCATC': 'febecf4c-6307-42df-8ca7-869191bbc73e',
 'ODL': '2c092617-c1be-47c5-8714-a430cd6b6747',
 'SB1NO': 'fa3f6ae4-592b-4ba6-8f87-31b5a4ea3727',
 'KMCP': '012e2b34-764a-49e9-a856-3bcf4bb4e1cc',
 'TIETO': '4591f419-44c7-4417-a16f-8350d2219097',
 'ENDUR': 'a3e42b15-273b-49a9-bbdf-8fc2721f371b',
 'STRO': 'b8f3df85-22c5-4ad0-8a15-ae02242543c0',
 'VEND': 'db3ec799-9f68-4cc6-9853-e0359c1ac965',
 'REACH': '537909d1-1bf3-4ff7-91d3-7ff588b876c3',
 'SALME': '935cd444-5238-425c-bf46-2a05511ec9b4',
 'BONHR': 'b59f42b8-3d1b-4576-83f1-f48d983724b3',
 'KOG': 'da74fc33-4c13-4549-a392-1a9ca3325066',
 'IOX': 'f59bc8d3-62fe-4383-8335-d11fbf2240be',
 'YAR': '8b19d7ec-1e35-4dd9-95c3-cc324a851e66',
 'PRS': 'd4fff353-09e8-4d7c-99e4-96ee2541a1d2',
 'NAPA': '1509c2ca-df31-494b-b4b1-0ed28765d172',
 'SBO': 'f3629e39-590f-49cb-8cf1-b0e11d13e06b',
 'META': '2ded042e-18a0-4288-b56d-f5ebdadaf311',
 'ATEA': '573c5f7d-4b73-44c9-84d5-c17564fb1903',
 'CONTX': '5b906c54-3a68-4d99-aced-871021fd14a1',
 'AKH': '2bc7e60e-f9bc-4a8f-b684-118e1d572935',
 'MULTI': 'a9888de1-c7c8-4d4b-89a4-c794b5442a4d',
 'PARB': 'de4b047a-8ad7-4ad2-a7c5-7a1445205bb0',
 'BMA': '472db18b-ee68-42c9-8f43-833ebc3831cb',
 'VAR': '04d0f7fa-ec99-4414-b87d-f25116d81d63',
 'ODF': '9aef5575-1576-4801-bf37-508930149437',
 'AFG': '63b824c5-8f38-4b49-9a9f-7e583ddf2a9d',
 'ARR': 'da7ee442-5350-4eaa-8653-bded9240006c',
 'KID': 'fb240d44-d733-476a-9e8a-dc52b9cde0bd',
 'MELG': 'a6c8dfb9-8480-48ee-9944-d57cb0408a0e',
 'SPOG': '27684fe4-052d-49de-b1bf-d3a20dc12278',
 'NOM': '6c94bfa2-b182-4c88-8416-d79ad6144ffa',
 'AAPL': 'b230f658-b9d4-4567-8e89-fa56f9c0744f',
 'ZAL': 'f8fc37b3-9b88-4aef-878d-fe2ab006ebf6',
 'SALM': 'f97aab04-fd36-47af-be03-1efd483fb9d8',
 'ELK': 'de748dad-507c-4980-9ff6-ca2b4b6bd25e',
 'GYL': '05e03814-d6a1-4b8a-a12e-775a02109262',
 'HSHP': '04e3b0e7-32f3-4642-b2e8-21d90548ae45',
 'KOA': '79bffc32-ab20-4f7d-847d-a3afd174f633',
 'AKBM': 'b9b82934-8d32-4562-8789-845d298c067c',
 'NYKD': '4c82a45f-30da-4513-85dd-f76ad23d5ca0',
 'SPOL': '1fb5d617-454e-4a9c-914a-12372f3d5aae',
 'BNOR': 'ad682530-72c7-42f2-85da-94d91458059b',
 'JAREN': 'e0956865-1ad5-4577-a487-9797da4f1a46',
 'BOR': '37551f46-f781-4e7a-95ee-2b18d031ed68',
 'PSE': 'b7455374-987f-4bb1-8902-155fb91e2584',
 'SDSD': 'e4f66e5c-fcda-45ff-a188-24e3fee44116',
 'NAS': 'e65fb9fd-b5a9-4fbd-bb6a-29d8c233ca14',
 'HEX': 'ee3c8a63-634d-42d6-8f67-30f441d0eb3b',
 'BWE': '0af3f10f-599c-463e-af01-681b1b9a08da',
 'EMGS': '61c9b951-a870-4018-bc82-22d79976b26f',
 'IDEX': '708044bd-2fcd-4fc3-9891-eb7054666a23',
 'AKRBP': '478014c6-d1be-40cf-ad94-5621f14defb3',
 'PEXIP': '7bb9896d-7601-4407-bdf7-12a17980f263',
 'NEL': 'd321e6d3-4d83-44d0-b106-c0f0ee7bc2fa',
 'RANA': '0e518c51-fe47-4da2-a065-dcc94e49fd59',
 'WSTEP': '6f0bc222-6ef3-45e5-bda4-796ab5119c0c',
 'TTWO': '02b81cc1-12b4-48c2-985e-1d294eb9a918',
 'VISTN': '4630a928-e7ca-4431-ad9d-10ef266182ce',
 'EQNR': '5ee6e30c-8658-476a-a65e-dd8f4da594ae',
 'CADLR': 'e64569a0-1305-4c68-80be-210588befebe',
 'ORK': '11551274-7e05-41f9-8cc1-f948623e89a4',
 'ELMRA': 'd630a0a7-a3aa-4444-a329-a085ce66d942',
 'AGLX': 'a68507e3-c412-4d43-9aa6-4dd1d098065d',
 'NEXT': 'e09919bb-6ebe-433a-a742-7c9272a60302',
 'TRMED': '29a1e91b-2ee5-4dae-81c2-87bc66a0f256',
 'DNO': '8ae18b69-27fe-4ef9-bfb1-8cfd6ca22d74',
 'AKER': 'fdaed71d-6748-4187-80b5-9840959a6fcc',
 'SOGN': '35b1aeb3-2d30-410f-82e9-663e7306705e',
 'ELO': '389281a0-56a7-4c2b-aafb-f9e4958499fe',
 'WAWI': '8df3333b-f217-4222-8907-73c584d6df0b',
 'BWO': 'f6b32ffe-2def-4b95-8937-c41078cd62bc',
 'TEL': 'eb1da7f8-37b6-470d-980b-cf7ddeb6746c',
 'BIEN': '720ca946-578d-4b94-9aed-0a79db729cf8',
 'BOUV': 'c8d38222-e135-48b4-8ee0-3ac1547e88d9',
 'ABG': '574883d5-6ea7-4a67-8dec-a6069e7e6185',
 'GJF': 'a620f2a8-4c28-4be1-8181-a3f68fe8b4c7',
 'SUBC': '2448439a-3a40-4d30-93b5-742780d266a1',
 'HAUTO': '3ddaa105-442f-45e7-9f9a-19635fd8fa1a',
 'VVL': '8beaa6cd-f3bd-4585-9fdd-c899fd5308b1',
 'EBAY': '8f991d12-2791-421d-8fae-c12538064f10',
 'NAVA': 'ee56f4f7-6b82-45fa-b107-d9224a3a6f31',
 'AURG': '09b4ae17-6fc1-473d-9d9a-a5505dd42746',
 'AZT': '2766b5f3-4673-4f0a-b186-cbf4c44eb619',
 'SOFF': '1b30a416-c929-454e-9746-9838b94de102',
 'AKVA': 'e3557b09-9bff-4dac-beae-53afe933b85e',
 'LSG': '9edeaf1a-03fc-4e73-93ac-fc83dddd8f9c',
 'SCANA': 'b0bc541b-a8d7-4b63-9e2c-71c3679aae7d',
 'TGS': '3da7a5ff-f455-410e-882c-2447d898307e',
 'HAVI': 'dc1f5b3f-ab28-4e27-8ab2-0d94a1460a01',
 'GOD': '6a6e14f3-0597-43d2-93bc-f9862370f44a',
 'HSPG': 'a6245c65-5f80-4412-98a9-fc56b68cf362',
 'RECSI': 'b6a223dc-8513-452d-b849-e3807d20e363',
 'ENTRA': '2cf5a0e3-1479-409a-b0fb-3f7aee848268',
 'OKEA': '63bbe4f1-5289-4d0a-b15e-42b59e04928f',
 'MPCC': 'b198c75b-4d2d-4c62-902e-2394863e311b',
 'PHO': 'dbcfcc04-bab6-407d-b87b-d8c6a1244002',
 'AUSS': '8ef90362-b178-444c-b546-5705260531c6',
 'JIN': 'e24fa533-3cdb-4fcc-adaa-7215cc87f8ed',
 'AMZN': '87710023-bd38-446e-b057-68d602d4135f',
 'SEA1': '54f4673c-dbcf-4332-a7cc-d162ce229a0f',
 'TOM': 'be84f9c0-d7c4-434e-8a95-15d3a5cf2e86',
 'MING': '1fb4377d-d355-4d67-8007-b4a5f2c40cad',
 'WWI': 'f9418770-70ee-463d-8e18-c03b13cda0d8',
 'VEI': '371733ae-c041-4de1-a4e2-b7ac3725ce70',
 'HBC': '25652f72-0ed6-4f21-8c70-1911b5ab9628',
 'SATS': '3ec72273-0251-458c-be7d-a47db366d08f',
 'NOL': '4ddf551a-a86e-4b52-8b52-3b3b5a64fa33',
 'CLOUD': 'a9981003-c2db-4900-a8a3-2fcb605c08db',
 'DNB': '2db847f9-e4af-413b-b930-8d7fab19800b',
 'NONG': '18a6af61-a38a-4327-ae26-9e06f9818cf4',
 'NVDA': '0c82d4af-0ac6-4000-a218-94e62cdec9d0',
 'HAFNI': '60bf1d98-cb25-40a0-a5f2-d6d0294bce2c',
 'SAGA': '8ab24aa1-f0e3-4e9c-8346-1d7515d53fbe',
 'OTL': 'bc2786d0-ed25-4abc-839c-4cb7661a2fce',
 'AUTO': '23efb041-2ebf-4d99-97a0-1297f9e5e268',
 'VOW': 'aaef6960-e143-45d2-a7bf-f77a1b16b132',
 'AKSO': 'cb060287-2146-4948-9b12-6abbeed50c23',
 'MSFT': 'a90266e9-f2dc-494a-a15c-5eba5b415efe',
 'MGN': '6fb2fce8-9edd-4513-9d02-e6a5be2f3517',
 'ACR': 'c71bb7f6-b775-4177-98bb-b4cadcc5f499',
 'PEN': '1fc814d7-03d9-49ed-8b1e-b8b12ad73b0f',
 'ZAP': '1d3d6efb-c5d1-4310-b40f-a9f8022c1c93',
 'BAKKA': '46856fb2-8341-4edc-8db2-65509a8da9e0',
 'POL': 'd1405e1e-18b2-47b6-9799-cb899416643a',
 'SOMA': 'd2a8b002-3d6a-4969-a490-10f8f4919bf2',
 'KIT': '36d7c530-6cb6-4056-a008-677223cc3acb',
 'GENT': 'e45410aa-b94b-46f3-94b5-49d2796816ec',
 'PROT': '06e587ee-d1a4-4b92-bd5c-a5f7d1f50110',
 'ENSU': '3399b4fa-3df4-4dab-99ad-0f638350dde5',
 'AFK': '94c1363e-e019-4896-b95d-cda97d2d6a9f',
 'EIOF': '3c9d80d3-a387-4fdf-af9d-122f1cef141b',
 'NSKOG': 'd09c6db8-5473-44eb-8bfb-8a80a4769096',
 'FRO': '28997cac-ce32-4c11-b2f6-74ca6ac8199f',
 'QEC': '9ce70d8a-47e5-4215-a047-a604f19c6d87',
 'OET': '534ff93b-dab3-4608-aca6-e9749e962683',
 'AKAST': 'ed0a90bf-ac5d-4754-810c-ccf3297e9849',
 'NOD': '160cd21d-1edc-489c-a067-fc60ff3eeb17',
 'LINK': '87f3af1c-101f-4ea4-a16c-0e2a986319c1',
 'DELIA': 'ca53acde-4bf7-45e8-90c1-f25378030391',
 'SKUE': 'faf2f3c8-1f2e-43d9-9760-5304739e43b3',
 'SBNOR': 'f70101cf-c408-4c09-bf04-cc3e5f1ff993',
 'STB': '484e76ff-5884-4a02-8039-9c64124dd01c',
 'SOAG': '5f25131d-1714-4af5-bf85-ed58ceabd373',
 'MEDI': '5226f694-5f34-46e2-8ae9-32deb0155e71',
 'GOOG': '08d3ecea-8730-464a-beed-f4f4d930f887',
 'ELABS': 'b5e959f4-0712-4ec0-bfbf-98cde57faa69',
 'SNI': '139eb4e3-4226-41cb-9dcf-88198a014de6',
 'TEKNA': '8caaa379-3914-42bc-9591-fbd558a23fd0'}

In [61]:
symbol_e24tag_mapping["EQNR"]

'5ee6e30c-8658-476a-a65e-dd8f4da594ae'

In [66]:
nordnet_csv = pd.read_csv("../StocksPlatform/Services/Seeding/Data/nordnet_all_stocks.csv")
nordnet_csv["E24Tag"] = nordnet_csv["Symbol"].map(symbol_e24tag_mapping)
nordnet_csv.to_csv("../StocksPlatform/Services/Seeding/Data/nordnet_all_stocks.csv", index=False)